#include "wirepump/traits/trait.hpp"

#include "wirepump/traits/byte.hpp"
#include "wirepump/traits/char.hpp"
#include "wirepump/traits/enum.hpp"
#include "wirepump/traits/floating_point.hpp"
#include "wirepump/traits/signed_integers.hpp"
#include "wirepump/traits/string_view.hpp"
#include "wirepump/traits/string.hpp"
#include "wirepump/traits/tuple.hpp"
#include "wirepump/traits/to_tuple.hpp"
#include "wirepump/traits/unsigned_integers.hpp"
#include "wirepump/traits/variant.hpp"
#include "wirepump/traits/vector.hpp"
